# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_FData2.1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 800)
        MainWindow.setMouseTracking(False)
        MainWindow.setTabletTracking(False)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("margin: 0px;")
        MainWindow.setInputMethodHints(QtCore.Qt.ImhDialableCharactersOnly|QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhEmailCharactersOnly|QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhLatinOnly|QtCore.Qt.ImhLowercaseOnly|QtCore.Qt.ImhUppercaseOnly|QtCore.Qt.ImhUrlCharactersOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -8, 999, 1048))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setStyleSheet("")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 5, 0, 1, 1)
        self.widgetFiltre = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widgetFiltre.setMinimumSize(QtCore.QSize(0, 131))
        self.widgetFiltre.setMaximumSize(QtCore.QSize(16777215, 131))
        self.widgetFiltre.setStyleSheet("")
        self.widgetFiltre.setObjectName("widgetFiltre")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widgetFiltre)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_7 = QtWidgets.QWidget(self.widgetFiltre)
        self.widget_7.setMaximumSize(QtCore.QSize(150, 100))
        self.widget_7.setStyleSheet("")
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_32 = QtWidgets.QLabel(self.widget_7)
        self.label_32.setMinimumSize(QtCore.QSize(100, 16))
        self.label_32.setMaximumSize(QtCore.QSize(125, 16))
        self.label_32.setObjectName("label_32")
        self.gridLayout_12.addWidget(self.label_32, 0, 0, 1, 1)
        self.comboBoxSource = QtWidgets.QComboBox(self.widget_7)
        self.comboBoxSource.setMinimumSize(QtCore.QSize(100, 25))
        self.comboBoxSource.setMaximumSize(QtCore.QSize(125, 25))
        self.comboBoxSource.setStyleSheet("color: rgb(0, 0, 0);")
        self.comboBoxSource.setObjectName("comboBoxSource")
        self.comboBoxSource.addItem("")
        self.comboBoxSource.addItem("")
        self.gridLayout_12.addWidget(self.comboBoxSource, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget_7)
        self.groupBoxPeriode = QtWidgets.QGroupBox(self.widgetFiltre)
        self.groupBoxPeriode.setEnabled(True)
        self.groupBoxPeriode.setObjectName("groupBoxPeriode")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBoxPeriode)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.dateEditDebut = QtWidgets.QDateEdit(self.groupBoxPeriode)
        self.dateEditDebut.setMinimumSize(QtCore.QSize(0, 25))
        self.dateEditDebut.setStyleSheet("color: rgb(0, 0, 0);")
        self.dateEditDebut.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1752, 10, 1), QtCore.QTime(0, 0, 0)))
        self.dateEditDebut.setMinimumDate(QtCore.QDate(1752, 10, 1))
        self.dateEditDebut.setCalendarPopup(True)
        self.dateEditDebut.setDate(QtCore.QDate(2020, 1, 1))
        self.dateEditDebut.setObjectName("dateEditDebut")
        self.gridLayout_9.addWidget(self.dateEditDebut, 2, 1, 1, 1)
        self.radioButtonAll = QtWidgets.QRadioButton(self.groupBoxPeriode)
        self.radioButtonAll.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.radioButtonAll.setIconSize(QtCore.QSize(16, 16))
        self.radioButtonAll.setChecked(False)
        self.radioButtonAll.setObjectName("radioButtonAll")
        self.gridLayout_9.addWidget(self.radioButtonAll, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBoxPeriode)
        self.label_5.setObjectName("label_5")
        self.gridLayout_9.addWidget(self.label_5, 2, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem, 0, 1, 1, 1)
        self.dateEditFin = QtWidgets.QDateEdit(self.groupBoxPeriode)
        self.dateEditFin.setMinimumSize(QtCore.QSize(0, 25))
        self.dateEditFin.setStyleSheet("color: rgb(0, 0, 0);")
        self.dateEditFin.setMaximumDate(QtCore.QDate(2099, 1, 1))
        self.dateEditFin.setCalendarPopup(True)
        self.dateEditFin.setDate(QtCore.QDate(2020, 3, 1))
        self.dateEditFin.setObjectName("dateEditFin")
        self.gridLayout_9.addWidget(self.dateEditFin, 2, 4, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem1, 2, 2, 1, 1)
        self.pushButtonOkPeriode = QtWidgets.QPushButton(self.groupBoxPeriode)
        self.pushButtonOkPeriode.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButtonOkPeriode.setObjectName("pushButtonOkPeriode")
        self.gridLayout_9.addWidget(self.pushButtonOkPeriode, 5, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem2, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBoxPeriode)
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 2, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBoxPeriode)
        self.groupBoxFiltre = QtWidgets.QGroupBox(self.widgetFiltre)
        self.groupBoxFiltre.setObjectName("groupBoxFiltre")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBoxFiltre)
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem3, 4, 2, 1, 1)
        self.pushButtonOkFiltre = QtWidgets.QPushButton(self.groupBoxFiltre)
        self.pushButtonOkFiltre.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButtonOkFiltre.setObjectName("pushButtonOkFiltre")
        self.gridLayout_11.addWidget(self.pushButtonOkFiltre, 5, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem4, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBoxFiltre)
        self.label_3.setObjectName("label_3")
        self.gridLayout_11.addWidget(self.label_3, 2, 2, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem5, 2, 1, 1, 1)
        self.comboBoxSexe = QtWidgets.QComboBox(self.groupBoxFiltre)
        self.comboBoxSexe.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBoxSexe.setStyleSheet("color: rgb(0, 0, 0);")
        self.comboBoxSexe.setObjectName("comboBoxSexe")
        self.comboBoxSexe.addItem("")
        self.comboBoxSexe.addItem("")
        self.comboBoxSexe.addItem("")
        self.gridLayout_11.addWidget(self.comboBoxSexe, 3, 0, 1, 1)
        self.comboBoxPoste = QtWidgets.QComboBox(self.groupBoxFiltre)
        self.comboBoxPoste.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBoxPoste.setStyleSheet("color: rgb(0, 0, 0);")
        self.comboBoxPoste.setObjectName("comboBoxPoste")
        self.gridLayout_11.addWidget(self.comboBoxPoste, 3, 2, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.groupBoxFiltre)
        self.label_6.setObjectName("label_6")
        self.gridLayout_11.addWidget(self.label_6, 2, 0, 1, 1)
        self.radioButtonFiltre = QtWidgets.QRadioButton(self.groupBoxFiltre)
        self.radioButtonFiltre.setObjectName("radioButtonFiltre")
        self.gridLayout_11.addWidget(self.radioButtonFiltre, 5, 0, 1, 3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem6, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBoxFiltre)
        self.gridLayout_3.addWidget(self.widgetFiltre, 4, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 71))
        self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.labelMinstSante = QtWidgets.QLabel(self.widget_3)
        self.labelMinstSante.setMaximumSize(QtCore.QSize(61, 51))
        self.labelMinstSante.setText("")
        self.labelMinstSante.setPixmap(QtGui.QPixmap("images/téléchargement.png"))
        self.labelMinstSante.setScaledContents(True)
        self.labelMinstSante.setObjectName("labelMinstSante")
        self.gridLayout_4.addWidget(self.labelMinstSante, 0, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 0, 1, 1, 1)
        self.labelAppName = QtWidgets.QLabel(self.widget_3)
        self.labelAppName.setMaximumSize(QtCore.QSize(450, 16777215))
        self.labelAppName.setStyleSheet("font: 30pt \"MV Boli\";\n"
"color: rgb(6, 88, 47);")
        self.labelAppName.setObjectName("labelAppName")
        self.gridLayout_4.addWidget(self.labelAppName, 0, 0, 1, 1)
        self.labelDCDJ = QtWidgets.QLabel(self.widget_3)
        self.labelDCDJ.setMaximumSize(QtCore.QSize(141, 51))
        self.labelDCDJ.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelDCDJ.setText("")
        self.labelDCDJ.setPixmap(QtGui.QPixmap("images/DCDJ_logo_0.png"))
        self.labelDCDJ.setScaledContents(True)
        self.labelDCDJ.setObjectName("labelDCDJ")
        self.gridLayout_4.addWidget(self.labelDCDJ, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.widget_3, 2, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setStyleSheet("")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 3, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.scrollAreaWidgetContents)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 800))
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777215, 800))
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageAccueil = QtWidgets.QWidget()
        self.pageAccueil.setObjectName("pageAccueil")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.pageAccueil)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem8 = QtWidgets.QSpacerItem(20, 210, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem8, 0, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(72, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem9, 1, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(71, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem10, 1, 2, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.pageAccueil)
        self.widget_5.setMinimumSize(QtCore.QSize(802, 363))
        self.widget_5.setStyleSheet("border: 0.5px solid ;\n"
"border-right: 5px solid rgb(6, 88, 47) ;\n"
"border-bottom:3px solid rgb(6, 88, 47) ;\n"
"background-color: rgb(255, 255, 255);")
        self.widget_5.setObjectName("widget_5")
        self.label_13 = QtWidgets.QLabel(self.widget_5)
        self.label_13.setGeometry(QtCore.QRect(55, 55, 71, 61))
        self.label_13.setMaximumSize(QtCore.QSize(71, 61))
        self.label_13.setStyleSheet("border: 0px solid ;\n"
"")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("images/database.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.labelExtration = QtWidgets.QLabel(self.widget_5)
        self.labelExtration.setGeometry(QtCore.QRect(141, 61, 113, 19))
        self.labelExtration.setMaximumSize(QtCore.QSize(131, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.labelExtration.setFont(font)
        self.labelExtration.setStyleSheet("color: rgb(6, 88, 47);\n"
"font-weight: bold;\n"
"font-size:16px;\n"
"font-style : normal ;\n"
"border: 0px solid ;\n"
"")
        self.labelExtration.setObjectName("labelExtration")
        self.lineExt = QtWidgets.QFrame(self.widget_5)
        self.lineExt.setGeometry(QtCore.QRect(132, 60, 3, 50))
        self.lineExt.setMaximumSize(QtCore.QSize(3, 50))
        self.lineExt.setStyleSheet("border: 1px solid ;\n"
"")
        self.lineExt.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineExt.setLineWidth(1)
        self.lineExt.setMidLineWidth(0)
        self.lineExt.setFrameShape(QtWidgets.QFrame.VLine)
        self.lineExt.setObjectName("lineExt")
        self.labelExt1 = QtWidgets.QLabel(self.widget_5)
        self.labelExt1.setGeometry(QtCore.QRect(141, 97, 361, 16))
        self.labelExt1.setMaximumSize(QtCore.QSize(361, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.labelExt1.setFont(font)
        self.labelExt1.setStyleSheet("font-style : italic ;\n"
"border: 0px solid ;\n"
"")
        self.labelExt1.setObjectName("labelExt1")
        self.lineEditImporterFichier = QtWidgets.QLineEdit(self.widget_5)
        self.lineEditImporterFichier.setGeometry(QtCore.QRect(80, 170, 500, 30))
        self.lineEditImporterFichier.setMinimumSize(QtCore.QSize(500, 25))
        self.lineEditImporterFichier.setObjectName("lineEditImporterFichier")
        self.pushButtonFichier = QtWidgets.QPushButton(self.widget_5)
        self.pushButtonFichier.setGeometry(QtCore.QRect(610, 168, 100, 30))
        self.pushButtonFichier.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButtonFichier.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButtonFichier.setStyleSheet("background-color: rgb(6, 88, 47);\n"
"color: rgb(255, 255, 255);")
        self.pushButtonFichier.setObjectName("pushButtonFichier")
        self.pushButtonAnnuler = QtWidgets.QPushButton(self.widget_5)
        self.pushButtonAnnuler.setGeometry(QtCore.QRect(330, 230, 100, 30))
        self.pushButtonAnnuler.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButtonAnnuler.setMaximumSize(QtCore.QSize(150, 30))
        self.pushButtonAnnuler.setSizeIncrement(QtCore.QSize(30, 52))
        self.pushButtonAnnuler.setStyleSheet("background-color: rgb(6, 88, 47);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.pushButtonAnnuler.setObjectName("pushButtonAnnuler")
        self.pushButtonOK = QtWidgets.QPushButton(self.widget_5)
        self.pushButtonOK.setGeometry(QtCore.QRect(470, 230, 100, 30))
        self.pushButtonOK.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButtonOK.setMaximumSize(QtCore.QSize(150, 30))
        self.pushButtonOK.setStyleSheet("background-color: rgb(6, 88, 47);\n"
"color: rgb(255, 255, 255);")
        self.pushButtonOK.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.gridLayout_7.addWidget(self.widget_5, 1, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem11, 2, 1, 1, 1)
        self.stackedWidget.addWidget(self.pageAccueil)
        self.pageEnregistrement = QtWidgets.QWidget()
        self.pageEnregistrement.setObjectName("pageEnregistrement")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.pageEnregistrement)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem12 = QtWidgets.QSpacerItem(67, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem12, 0, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.pageEnregistrement)
        self.widget_6.setMinimumSize(QtCore.QSize(811, 721))
        self.widget_6.setStyleSheet("border: 10px solid rgb(6, 88, 47);\n"
"border-color: rgb(6, 88, 47);\n"
"")
        self.widget_6.setObjectName("widget_6")
        self.groupBoxGenerale = QtWidgets.QGroupBox(self.widget_6)
        self.groupBoxGenerale.setGeometry(QtCore.QRect(20, 30, 751, 141))
        self.groupBoxGenerale.setMinimumSize(QtCore.QSize(751, 141))
        self.groupBoxGenerale.setStyleSheet("color:  rgb(6, 88, 47);\n"
"border: 1px solid;\n"
"border-color: rgb(6, 88, 47);\n"
"color:  rgb(6, 88, 47);")
        self.groupBoxGenerale.setObjectName("groupBoxGenerale")
        self.comboBoxPosteEnreg = QtWidgets.QComboBox(self.groupBoxGenerale)
        self.comboBoxPosteEnreg.setGeometry(QtCore.QRect(190, 40, 311, 25))
        self.comboBoxPosteEnreg.setObjectName("comboBoxPosteEnreg")
        self.comboBoxPosteEnreg.addItem("")
        self.comboBoxPosteEnreg.addItem("")
        self.comboBoxPosteEnreg.addItem("")
        self.comboBoxPosteEnreg.addItem("")
        self.comboBoxPosteEnreg.addItem("")
        self.comboBoxPosteEnreg.addItem("")
        self.comboBoxPosteEnreg.addItem("")
        self.comboBoxPosteEnreg.addItem("")
        self.label_11 = QtWidgets.QLabel(self.groupBoxGenerale)
        self.label_11.setGeometry(QtCore.QRect(20, 47, 151, 16))
        self.label_11.setStyleSheet("border: 0px solid;")
        self.label_11.setObjectName("label_11")
        self.dateEditDateEnreg = QtWidgets.QDateEdit(self.groupBoxGenerale)
        self.dateEditDateEnreg.setGeometry(QtCore.QRect(190, 87, 121, 25))
        self.dateEditDateEnreg.setCalendarPopup(True)
        self.dateEditDateEnreg.setObjectName("dateEditDateEnreg")
        self.label_18 = QtWidgets.QLabel(self.groupBoxGenerale)
        self.label_18.setGeometry(QtCore.QRect(30, 93, 141, 16))
        self.label_18.setStyleSheet("border: 0px solid;")
        self.label_18.setObjectName("label_18")
        self.groupBoxPatient = QtWidgets.QGroupBox(self.widget_6)
        self.groupBoxPatient.setGeometry(QtCore.QRect(20, 190, 751, 231))
        self.groupBoxPatient.setMinimumSize(QtCore.QSize(751, 231))
        self.groupBoxPatient.setStyleSheet("color:  rgb(6, 88, 47);\n"
"border: 1px solid;\n"
"border-color: rgb(6, 88, 47);\n"
"")
        self.groupBoxPatient.setObjectName("groupBoxPatient")
        self.lineEditCodePatient = QtWidgets.QLineEdit(self.groupBoxPatient)
        self.lineEditCodePatient.setGeometry(QtCore.QRect(220, 30, 241, 25))
        self.lineEditCodePatient.setObjectName("lineEditCodePatient")
        self.label_19 = QtWidgets.QLabel(self.groupBoxPatient)
        self.label_19.setGeometry(QtCore.QRect(70, 38, 131, 16))
        self.label_19.setStyleSheet("border: 0px solid;")
        self.label_19.setObjectName("label_19")
        self.comboBoxSexeEnreg = QtWidgets.QComboBox(self.groupBoxPatient)
        self.comboBoxSexeEnreg.setGeometry(QtCore.QRect(220, 70, 101, 25))
        self.comboBoxSexeEnreg.setObjectName("comboBoxSexeEnreg")
        self.comboBoxSexeEnreg.addItem("")
        self.comboBoxSexeEnreg.addItem("")
        self.label_20 = QtWidgets.QLabel(self.groupBoxPatient)
        self.label_20.setGeometry(QtCore.QRect(150, 77, 51, 20))
        self.label_20.setStyleSheet("border: 0px solid;")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBoxPatient)
        self.label_21.setGeometry(QtCore.QRect(150, 124, 47, 21))
        self.label_21.setStyleSheet("border: 0px solid;")
        self.label_21.setObjectName("label_21")
        self.spinBoxAge = QtWidgets.QSpinBox(self.groupBoxPatient)
        self.spinBoxAge.setGeometry(QtCore.QRect(220, 120, 61, 25))
        self.spinBoxAge.setPrefix("")
        self.spinBoxAge.setMinimum(1)
        self.spinBoxAge.setProperty("value", 1)
        self.spinBoxAge.setObjectName("spinBoxAge")
        self.comboBoxGandeur = QtWidgets.QComboBox(self.groupBoxPatient)
        self.comboBoxGandeur.setGeometry(QtCore.QRect(480, 120, 121, 25))
        self.comboBoxGandeur.setObjectName("comboBoxGandeur")
        self.comboBoxGandeur.addItem("")
        self.comboBoxGandeur.addItem("")
        self.comboBoxGandeur.addItem("")
        self.comboBoxGandeur.addItem("")
        self.label_23 = QtWidgets.QLabel(self.groupBoxPatient)
        self.label_23.setGeometry(QtCore.QRect(320, 127, 141, 21))
        self.label_23.setStyleSheet("\n"
"border: 0px solid;")
        self.label_23.setObjectName("label_23")
        self.comboBoxTrancheAge = QtWidgets.QComboBox(self.groupBoxPatient)
        self.comboBoxTrancheAge.setGeometry(QtCore.QRect(220, 170, 141, 25))
        self.comboBoxTrancheAge.setEditable(False)
        self.comboBoxTrancheAge.setDuplicatesEnabled(False)
        self.comboBoxTrancheAge.setObjectName("comboBoxTrancheAge")
        self.comboBoxTrancheAge.addItem("")
        self.comboBoxTrancheAge.addItem("")
        self.comboBoxTrancheAge.addItem("")
        self.comboBoxTrancheAge.addItem("")
        self.comboBoxTrancheAge.addItem("")
        self.comboBoxTrancheAge.addItem("")
        self.comboBoxTrancheAge.addItem("")
        self.comboBoxTrancheAge.addItem("")
        self.comboBoxTrancheAge.addItem("")
        self.comboBoxTrancheAge.addItem("")
        self.label_22 = QtWidgets.QLabel(self.groupBoxPatient)
        self.label_22.setGeometry(QtCore.QRect(10, 178, 191, 16))
        self.label_22.setStyleSheet("border: 0px solid;")
        self.label_22.setObjectName("label_22")
        self.groupBoxDepistage = QtWidgets.QGroupBox(self.widget_6)
        self.groupBoxDepistage.setGeometry(QtCore.QRect(20, 450, 751, 221))
        self.groupBoxDepistage.setMinimumSize(QtCore.QSize(751, 221))
        self.groupBoxDepistage.setStyleSheet("color:  rgb(6, 88, 47);\n"
"border: 1px solid;\n"
"border-color: rgb(6, 88, 47);\n"
"color:  rgb(6, 88, 47);")
        self.groupBoxDepistage.setCheckable(False)
        self.groupBoxDepistage.setObjectName("groupBoxDepistage")
        self.comboBoxConseilDep = QtWidgets.QComboBox(self.groupBoxDepistage)
        self.comboBoxConseilDep.setGeometry(QtCore.QRect(190, 30, 69, 25))
        self.comboBoxConseilDep.setObjectName("comboBoxConseilDep")
        self.comboBoxConseilDep.addItem("")
        self.comboBoxConseilDep.addItem("")
        self.label_24 = QtWidgets.QLabel(self.groupBoxDepistage)
        self.label_24.setGeometry(QtCore.QRect(10, 35, 171, 21))
        self.label_24.setStyleSheet("border: 0px solid;")
        self.label_24.setObjectName("label_24")
        self.comboBoxEffectDep = QtWidgets.QComboBox(self.groupBoxDepistage)
        self.comboBoxEffectDep.setGeometry(QtCore.QRect(610, 30, 69, 25))
        self.comboBoxEffectDep.setObjectName("comboBoxEffectDep")
        self.comboBoxEffectDep.addItem("")
        self.comboBoxEffectDep.addItem("")
        self.label_25 = QtWidgets.QLabel(self.groupBoxDepistage)
        self.label_25.setGeometry(QtCore.QRect(430, 38, 171, 16))
        self.label_25.setStyleSheet("border: 0px solid;")
        self.label_25.setObjectName("label_25")
        self.comboBoxConseilerAvResult = QtWidgets.QComboBox(self.groupBoxDepistage)
        self.comboBoxConseilerAvResult.setGeometry(QtCore.QRect(350, 80, 69, 25))
        self.comboBoxConseilerAvResult.setObjectName("comboBoxConseilerAvResult")
        self.comboBoxConseilerAvResult.addItem("")
        self.comboBoxConseilerAvResult.addItem("")
        self.label_26 = QtWidgets.QLabel(self.groupBoxDepistage)
        self.label_26.setGeometry(QtCore.QRect(10, 87, 331, 16))
        self.label_26.setStyleSheet("border: 0px solid;")
        self.label_26.setObjectName("label_26")
        self.comboBoxResultat = QtWidgets.QComboBox(self.groupBoxDepistage)
        self.comboBoxResultat.setGeometry(QtCore.QRect(240, 130, 121, 25))
        self.comboBoxResultat.setObjectName("comboBoxResultat")
        self.comboBoxResultat.addItem("")
        self.comboBoxResultat.addItem("")
        self.comboBoxResultat.addItem("")
        self.comboBoxResultat.addItem("")
        self.label_27 = QtWidgets.QLabel(self.groupBoxDepistage)
        self.label_27.setGeometry(QtCore.QRect(10, 137, 221, 16))
        self.label_27.setStyleSheet("border: 0px solid;")
        self.label_27.setObjectName("label_27")
        self.comboBoxPositifConnaisResultat = QtWidgets.QComboBox(self.groupBoxDepistage)
        self.comboBoxPositifConnaisResultat.setGeometry(QtCore.QRect(640, 130, 69, 25))
        self.comboBoxPositifConnaisResultat.setObjectName("comboBoxPositifConnaisResultat")
        self.comboBoxPositifConnaisResultat.addItem("")
        self.comboBoxPositifConnaisResultat.addItem("")
        self.label_28 = QtWidgets.QLabel(self.groupBoxDepistage)
        self.label_28.setGeometry(QtCore.QRect(410, 136, 231, 20))
        self.label_28.setStyleSheet("border: 0px solid;")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBoxDepistage)
        self.label_29.setGeometry(QtCore.QRect(10, 186, 211, 16))
        self.label_29.setStyleSheet("border: 0px solid;")
        self.label_29.setObjectName("label_29")
        self.comboBoxBeneficiantCD4 = QtWidgets.QComboBox(self.groupBoxDepistage)
        self.comboBoxBeneficiantCD4.setGeometry(QtCore.QRect(240, 180, 69, 25))
        self.comboBoxBeneficiantCD4.setObjectName("comboBoxBeneficiantCD4")
        self.comboBoxBeneficiantCD4.addItem("")
        self.comboBoxBeneficiantCD4.addItem("")
        self.pushButtonEnregistrer = QtWidgets.QPushButton(self.widget_6)
        self.pushButtonEnregistrer.setGeometry(QtCore.QRect(570, 707, 100, 30))
        self.pushButtonEnregistrer.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButtonEnregistrer.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButtonEnregistrer.setStyleSheet("background-color: rgb(6, 88, 47);\n"
"color: rgb(255, 255, 255);\n"
"border: 0px solid;")
        self.pushButtonEnregistrer.setObjectName("pushButtonEnregistrer")
        self.pushButtonAnnuler2 = QtWidgets.QPushButton(self.widget_6)
        self.pushButtonAnnuler2.setGeometry(QtCore.QRect(428, 707, 100, 30))
        self.pushButtonAnnuler2.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButtonAnnuler2.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButtonAnnuler2.setStyleSheet("background-color: rgb(6, 88, 47);\n"
"color: rgb(255, 255, 255);\n"
"border: 0px solid;")
        self.pushButtonAnnuler2.setObjectName("pushButtonAnnuler2")
        self.gridLayout_8.addWidget(self.widget_6, 0, 1, 2, 1)
        spacerItem13 = QtWidgets.QSpacerItem(67, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem13, 1, 2, 1, 1)
        self.stackedWidget.addWidget(self.pageEnregistrement)
        self.pageView = QtWidgets.QWidget()
        self.pageView.setObjectName("pageView")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.pageView)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.tableWidgetData = QtWidgets.QTableWidget(self.pageView)
        self.tableWidgetData.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidgetData.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidgetData.setAutoScroll(True)
        self.tableWidgetData.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetData.setTabKeyNavigation(True)
        self.tableWidgetData.setProperty("showDropIndicator", True)
        self.tableWidgetData.setDragEnabled(False)
        self.tableWidgetData.setDragDropOverwriteMode(True)
        self.tableWidgetData.setAlternatingRowColors(True)
        self.tableWidgetData.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableWidgetData.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidgetData.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidgetData.setShowGrid(True)
        self.tableWidgetData.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidgetData.setWordWrap(True)
        self.tableWidgetData.setCornerButtonEnabled(True)
        self.tableWidgetData.setRowCount(31)
        self.tableWidgetData.setObjectName("tableWidgetData")
        self.tableWidgetData.setColumnCount(11)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetData.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetData.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetData.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetData.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetData.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetData.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetData.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetData.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetData.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetData.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetData.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetData.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetData.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetData.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetData.setItem(1, 1, item)
        self.tableWidgetData.horizontalHeader().setVisible(False)
        self.tableWidgetData.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetData.horizontalHeader().setHighlightSections(True)
        self.tableWidgetData.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetData.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetData.verticalHeader().setVisible(False)
        self.tableWidgetData.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidgetData.verticalHeader().setHighlightSections(False)
        self.tableWidgetData.verticalHeader().setSortIndicatorShown(False)
        self.tableWidgetData.verticalHeader().setStretchLastSection(False)
        self.gridLayout_10.addWidget(self.tableWidgetData, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageView)
        self.pageGraph = QtWidgets.QWidget()
        self.pageGraph.setObjectName("pageGraph")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.pageGraph)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.graphicsView1 = QtWidgets.QGraphicsView(self.pageGraph)
        self.graphicsView1.setObjectName("graphicsView1")
        self.gridLayout_2.addWidget(self.graphicsView1, 0, 0, 1, 1)
        self.graphicsView2 = QtWidgets.QGraphicsView(self.pageGraph)
        self.graphicsView2.setObjectName("graphicsView2")
        self.gridLayout_2.addWidget(self.graphicsView2, 0, 1, 1, 1)
        self.graphicsView3 = QtWidgets.QGraphicsView(self.pageGraph)
        self.graphicsView3.setObjectName("graphicsView3")
        self.gridLayout_2.addWidget(self.graphicsView3, 1, 0, 1, 1)
        self.graphicsView4 = QtWidgets.QGraphicsView(self.pageGraph)
        self.graphicsView4.setObjectName("graphicsView4")
        self.gridLayout_2.addWidget(self.graphicsView4, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.pageGraph)
        self.pageExtraction = QtWidgets.QWidget()
        self.pageExtraction.setObjectName("pageExtraction")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.pageExtraction)
        self.gridLayout_14.setObjectName("gridLayout_14")
        spacerItem14 = QtWidgets.QSpacerItem(20, 162, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem14, 0, 2, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(72, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem15, 1, 0, 1, 1)
        self.widget_9 = QtWidgets.QWidget(self.pageExtraction)
        self.widget_9.setMinimumSize(QtCore.QSize(802, 441))
        self.widget_9.setStyleSheet("border: 0.5px solid ;\n"
"border-right: 5px solid rgb(6, 88, 47) ;\n"
"border-bottom:3px solid rgb(6, 88, 47) ;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.widget_9.setObjectName("widget_9")
        self.label_10 = QtWidgets.QLabel(self.widget_9)
        self.label_10.setGeometry(QtCore.QRect(200, 320, 401, 20))
        self.label_10.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"font-style : italic ;\n"
"border: 0px;")
        self.label_10.setObjectName("label_10")
        self.lineEditExporter = QtWidgets.QLineEdit(self.widget_9)
        self.lineEditExporter.setGeometry(QtCore.QRect(80, 220, 500, 30))
        self.lineEditExporter.setObjectName("lineEditExporter")
        self.labelExtration_2 = QtWidgets.QLabel(self.widget_9)
        self.labelExtration_2.setGeometry(QtCore.QRect(170, 60, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.labelExtration_2.setFont(font)
        self.labelExtration_2.setStyleSheet("color: rgb(6, 88, 47);\n"
"font-weight: bold;\n"
"font-size:16px;\n"
"font-style : normal ;\n"
"border: 0px;")
        self.labelExtration_2.setObjectName("labelExtration_2")
        self.label_9 = QtWidgets.QLabel(self.widget_9)
        self.label_9.setGeometry(QtCore.QRect(140, 310, 51, 41))
        self.label_9.setStyleSheet("border: 0px;")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("images/info.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_16 = QtWidgets.QLabel(self.widget_9)
        self.label_16.setGeometry(QtCore.QRect(70, 50, 71, 61))
        self.label_16.setStyleSheet("border: 0px;")
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("images/yesterday1.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.pushButtonExporter2 = QtWidgets.QPushButton(self.widget_9)
        self.pushButtonExporter2.setGeometry(QtCore.QRect(600, 220, 100, 30))
        self.pushButtonExporter2.setStyleSheet("background-color: rgb(6, 88, 47);\n"
"color: rgb(255, 255, 255);\n"
"border: 0px;")
        self.pushButtonExporter2.setObjectName("pushButtonExporter2")
        self.label_8 = QtWidgets.QLabel(self.widget_9)
        self.label_8.setGeometry(QtCore.QRect(130, 300, 491, 61))
        self.label_8.setStyleSheet("border: 1px solid black ;")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(self.widget_9)
        self.label_7.setGeometry(QtCore.QRect(80, 190, 301, 21))
        self.label_7.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"font-style : italic ;\n"
"border: 0px;\n"
"")
        self.label_7.setObjectName("label_7")
        self.lineExt_2 = QtWidgets.QFrame(self.widget_9)
        self.lineExt_2.setGeometry(QtCore.QRect(150, 60, 3, 50))
        self.lineExt_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.lineExt_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineExt_2.setObjectName("lineExt_2")
        self.labelExt1_2 = QtWidgets.QLabel(self.widget_9)
        self.labelExt1_2.setGeometry(QtCore.QRect(170, 90, 361, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.labelExt1_2.setFont(font)
        self.labelExt1_2.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"font-style : italic ;\n"
"border: 0px;")
        self.labelExt1_2.setObjectName("labelExt1_2")
        self.label_8.raise_()
        self.label_10.raise_()
        self.lineEditExporter.raise_()
        self.labelExtration_2.raise_()
        self.label_9.raise_()
        self.label_16.raise_()
        self.pushButtonExporter2.raise_()
        self.label_7.raise_()
        self.lineExt_2.raise_()
        self.labelExt1_2.raise_()
        self.gridLayout_14.addWidget(self.widget_9, 1, 1, 2, 2)
        spacerItem16 = QtWidgets.QSpacerItem(71, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem16, 2, 3, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 161, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem17, 3, 1, 1, 1)
        self.stackedWidget.addWidget(self.pageExtraction)
        self.gridLayout_3.addWidget(self.stackedWidget, 6, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 5, 2, 1, 1)
        self.widget_8 = QtWidgets.QWidget(self.centralwidget)
        self.widget_8.setMinimumSize(QtCore.QSize(211, 0))
        self.widget_8.setStyleSheet("margin: 0px;\n"
"background-color: rgb(6, 88, 47);")
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.labelDCDJ2 = QtWidgets.QLabel(self.widget_8)
        self.labelDCDJ2.setMinimumSize(QtCore.QSize(181, 51))
        self.labelDCDJ2.setMaximumSize(QtCore.QSize(181, 51))
        self.labelDCDJ2.setStyleSheet("background-color: rgb(6, 88, 47);")
        self.labelDCDJ2.setText("")
        self.labelDCDJ2.setPixmap(QtGui.QPixmap("images/DCDJ_logo_0.png"))
        self.labelDCDJ2.setScaledContents(True)
        self.labelDCDJ2.setObjectName("labelDCDJ2")
        self.gridLayout_13.addWidget(self.labelDCDJ2, 4, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.widget_8)
        self.widget.setMinimumSize(QtCore.QSize(0, 150))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 150))
        self.widget.setObjectName("widget")
        self.labelLogo3 = QtWidgets.QLabel(self.widget)
        self.labelLogo3.setGeometry(QtCore.QRect(100, 40, 53, 31))
        self.labelLogo3.setStyleSheet("font: 18pt \"MV Boli\";\n"
"color: rgb(255, 85, 0);")
        self.labelLogo3.setObjectName("labelLogo3")
        self.labelLogo5 = QtWidgets.QLabel(self.widget)
        self.labelLogo5.setGeometry(QtCore.QRect(95, 67, 47, 31))
        self.labelLogo5.setStyleSheet("font: 16pt \"MV Boli\";\n"
"color: rgb(255, 255, 255);")
        self.labelLogo5.setObjectName("labelLogo5")
        self.labelLogo2 = QtWidgets.QLabel(self.widget)
        self.labelLogo2.setGeometry(QtCore.QRect(65, 24, 81, 81))
        self.labelLogo2.setStyleSheet("font: 60pt \"MV Boli\";\n"
"color: rgb(255, 255, 255);")
        self.labelLogo2.setObjectName("labelLogo2")
        self.labelLogo1 = QtWidgets.QLabel(self.widget)
        self.labelLogo1.setGeometry(QtCore.QRect(15, 34, 51, 41))
        self.labelLogo1.setStyleSheet("font: 18pt \"MV Boli\";\n"
"color: rgb(255, 85, 0);")
        self.labelLogo1.setObjectName("labelLogo1")
        self.labelLogo4 = QtWidgets.QLabel(self.widget)
        self.labelLogo4.setGeometry(QtCore.QRect(45, 64, 41, 31))
        self.labelLogo4.setText("")
        self.labelLogo4.setPixmap(QtGui.QPixmap("images/upload1 (2).png"))
        self.labelLogo4.setScaledContents(True)
        self.labelLogo4.setObjectName("labelLogo4")
        self.labelLogo2.raise_()
        self.labelLogo3.raise_()
        self.labelLogo5.raise_()
        self.labelLogo1.raise_()
        self.labelLogo4.raise_()
        self.gridLayout_13.addWidget(self.widget, 0, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 300, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem18, 3, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.widget_8)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 300))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 300))
        self.widget_2.setStyleSheet("margin:0px;\n"
"padding: 0px;")
        self.widget_2.setObjectName("widget_2")
        self.pushButtonEnregistrement = QtWidgets.QPushButton(self.widget_2)
        self.pushButtonEnregistrement.setGeometry(QtCore.QRect(0, 70, 201, 40))
        self.pushButtonEnregistrement.setStyleSheet("QPushButton{\n"
"    background-color: rgb(6, 88, 47);\n"
"    font: 87 12pt \"Segoe UI Black\";\n"
"    color: rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"    text-align: left;\n"
"    border: 0px solid;\n"
"    font-style : italic ;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(5, 75, 40);\n"
"    border-left: 5px solid;\n"
"    border-left-color: rgb(85, 255, 0);\n"
"}")
        self.pushButtonEnregistrement.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonEnregistrement.setFlat(True)
        self.pushButtonEnregistrement.setObjectName("pushButtonEnregistrement")
        self.pushButtonAccueil = QtWidgets.QPushButton(self.widget_2)
        self.pushButtonAccueil.setGeometry(QtCore.QRect(0, 30, 191, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButtonAccueil.setFont(font)
        self.pushButtonAccueil.setAcceptDrops(False)
        self.pushButtonAccueil.setAutoFillBackground(False)
        self.pushButtonAccueil.setStyleSheet("QPushButton{\n"
"    background-color: rgb(6, 88, 47);\n"
"    font: 87 12pt \"Segoe UI Black\";\n"
"    color: rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"    text-align: left;\n"
"    border: 0px solid;\n"
"    font-style : italic ;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(5, 75, 40);\n"
"    \n"
"    border-left: 5px solid;\n"
"    border-left-color: rgb(85, 255, 0);\n"
"}")
        self.pushButtonAccueil.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonAccueil.setCheckable(False)
        self.pushButtonAccueil.setChecked(False)
        self.pushButtonAccueil.setAutoRepeat(False)
        self.pushButtonAccueil.setAutoExclusive(False)
        self.pushButtonAccueil.setAutoDefault(False)
        self.pushButtonAccueil.setDefault(False)
        self.pushButtonAccueil.setFlat(False)
        self.pushButtonAccueil.setObjectName("pushButtonAccueil")
        self.pushButtonVisualisation = QtWidgets.QPushButton(self.widget_2)
        self.pushButtonVisualisation.setGeometry(QtCore.QRect(0, 150, 201, 40))
        self.pushButtonVisualisation.setStyleSheet("QPushButton{\n"
"    background-color: rgb(6, 88, 47);\n"
"    font: 87 12pt \"Segoe UI Black\";\n"
"    color: rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"    text-align: left;\n"
"    border: 0px solid;\n"
"    font-style : italic ;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(5, 75, 40);\n"
"    border-left: 5px solid;\n"
"    border-left-color: rgb(85, 255, 0);\n"
"}")
        self.pushButtonVisualisation.setFlat(True)
        self.pushButtonVisualisation.setObjectName("pushButtonVisualisation")
        self.pushButtonExporter = QtWidgets.QPushButton(self.widget_2)
        self.pushButtonExporter.setGeometry(QtCore.QRect(0, 190, 201, 40))
        self.pushButtonExporter.setStyleSheet("QPushButton{\n"
"    background-color: rgb(6, 88, 47);\n"
"    font: 87 12pt \"Segoe UI Black\";\n"
"    color: rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"    text-align: left;\n"
"    border: 0px solid;\n"
"    font-style : italic ;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(5, 75, 40);\n"
"    border-left: 5px solid;\n"
"    border-left-color: rgb(85, 255, 0);\n"
"}")
        self.pushButtonExporter.setFlat(True)
        self.pushButtonExporter.setObjectName("pushButtonExporter")
        self.pushButtonDonnees = QtWidgets.QPushButton(self.widget_2)
        self.pushButtonDonnees.setGeometry(QtCore.QRect(0, 110, 201, 40))
        self.pushButtonDonnees.setStyleSheet("QPushButton{background-color: rgb(6, 88, 47); font: 87 12pt \"Segoe UI Black\"; color: rgb(255, 255, 255); font-weight: bold; text-align: left; border: 0px solid; font-style : italic ; } QPushButton:hover{ background-color: rgb(19, 252, 136); background-color: rgb(5, 75, 40); border-left: 5px solid; border-left-color: rgb(85, 255, 0);}")
        self.pushButtonDonnees.setFlat(True)
        self.pushButtonDonnees.setObjectName("pushButtonDonnees")
        self.gridLayout_13.addWidget(self.widget_2, 2, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_13.addItem(spacerItem19, 5, 0, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem20, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_8, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.comboBoxSexe.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Reporting Tool"))
        self.label_32.setText(_translate("MainWindow", "Source"))
        self.comboBoxSource.setItemText(0, _translate("MainWindow", "Excel"))
        self.comboBoxSource.setItemText(1, _translate("MainWindow", "BD"))
        self.groupBoxPeriode.setTitle(_translate("MainWindow", "Période"))
        self.dateEditDebut.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.radioButtonAll.setText(_translate("MainWindow", "Tout"))
        self.label_5.setText(_translate("MainWindow", "Fin :"))
        self.dateEditFin.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.pushButtonOkPeriode.setText(_translate("MainWindow", "ok"))
        self.label_4.setText(_translate("MainWindow", "Debut :"))
        self.groupBoxFiltre.setTitle(_translate("MainWindow", "Filtre"))
        self.pushButtonOkFiltre.setText(_translate("MainWindow", "ok"))
        self.label_3.setText(_translate("MainWindow", "Poste de dépis."))
        self.comboBoxSexe.setItemText(0, _translate("MainWindow", "Tout"))
        self.comboBoxSexe.setItemText(1, _translate("MainWindow", "Masculin"))
        self.comboBoxSexe.setItemText(2, _translate("MainWindow", "Feminin"))
        self.label_6.setText(_translate("MainWindow", "Sexe"))
        self.radioButtonFiltre.setText(_translate("MainWindow", "Désactiver les filtres"))
        self.labelAppName.setText(_translate("MainWindow", "Outil de Rapportage"))
        self.labelExtration.setText(_translate("MainWindow", "Importation "))
        self.labelExt1.setText(_translate("MainWindow", "Importer le fichier excel (*.xlsx, *.xls) à traiter."))
        self.pushButtonFichier.setText(_translate("MainWindow", "Fichier"))
        self.pushButtonAnnuler.setText(_translate("MainWindow", "annuler"))
        self.pushButtonOK.setText(_translate("MainWindow", "ok"))
        self.groupBoxGenerale.setTitle(_translate("MainWindow", "Générale"))
        self.comboBoxPosteEnreg.setItemText(0, _translate("MainWindow", "IST"))
        self.comboBoxPosteEnreg.setItemText(1, _translate("MainWindow", "Tuberculose"))
        self.comboBoxPosteEnreg.setItemText(2, _translate("MainWindow", "CPN2 et Plus + Accouch + CPoN"))
        self.comboBoxPosteEnreg.setItemText(3, _translate("MainWindow", "Hospitalisation"))
        self.comboBoxPosteEnreg.setItemText(4, _translate("MainWindow", "Index testing"))
        self.comboBoxPosteEnreg.setItemText(5, _translate("MainWindow", "Urgence"))
        self.comboBoxPosteEnreg.setItemText(6, _translate("MainWindow", "Malnutrition"))
        self.comboBoxPosteEnreg.setItemText(7, _translate("MainWindow", "AUTRE CDIP"))
        self.label_11.setText(_translate("MainWindow", "Poste de dépistage :"))
        self.dateEditDateEnreg.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.label_18.setText(_translate("MainWindow", "Date de dépistage :"))
        self.groupBoxPatient.setTitle(_translate("MainWindow", "Patient"))
        self.label_19.setText(_translate("MainWindow", "Code du patient :"))
        self.comboBoxSexeEnreg.setItemText(0, _translate("MainWindow", "Masculin"))
        self.comboBoxSexeEnreg.setItemText(1, _translate("MainWindow", "Feminin"))
        self.label_20.setText(_translate("MainWindow", "Sexe :"))
        self.label_21.setText(_translate("MainWindow", "Age :"))
        self.comboBoxGandeur.setItemText(0, _translate("MainWindow", "Années"))
        self.comboBoxGandeur.setItemText(1, _translate("MainWindow", "Mois"))
        self.comboBoxGandeur.setItemText(2, _translate("MainWindow", "Semaines"))
        self.comboBoxGandeur.setItemText(3, _translate("MainWindow", "Jours"))
        self.label_23.setText(_translate("MainWindow", "Grandeur de l\'age :"))
        self.comboBoxTrancheAge.setItemText(0, _translate("MainWindow", "0-4"))
        self.comboBoxTrancheAge.setItemText(1, _translate("MainWindow", "5-9"))
        self.comboBoxTrancheAge.setItemText(2, _translate("MainWindow", "10-14"))
        self.comboBoxTrancheAge.setItemText(3, _translate("MainWindow", "15-19"))
        self.comboBoxTrancheAge.setItemText(4, _translate("MainWindow", "20-24"))
        self.comboBoxTrancheAge.setItemText(5, _translate("MainWindow", "30-34"))
        self.comboBoxTrancheAge.setItemText(6, _translate("MainWindow", "35-39"))
        self.comboBoxTrancheAge.setItemText(7, _translate("MainWindow", "40-44"))
        self.comboBoxTrancheAge.setItemText(8, _translate("MainWindow", "45-49"))
        self.comboBoxTrancheAge.setItemText(9, _translate("MainWindow", "50 et plus"))
        self.label_22.setText(_translate("MainWindow", "Préciser la tranche d\'age :"))
        self.groupBoxDepistage.setTitle(_translate("MainWindow", "Information sur le test de dépistage"))
        self.comboBoxConseilDep.setItemText(0, _translate("MainWindow", "Oui"))
        self.comboBoxConseilDep.setItemText(1, _translate("MainWindow", "Non"))
        self.label_24.setText(_translate("MainWindow", "Conseiller pour le test :"))
        self.comboBoxEffectDep.setItemText(0, _translate("MainWindow", "Oui"))
        self.comboBoxEffectDep.setItemText(1, _translate("MainWindow", "Non"))
        self.label_25.setText(_translate("MainWindow", "Effectivement dépisté :"))
        self.comboBoxConseilerAvResult.setItemText(0, _translate("MainWindow", "Oui"))
        self.comboBoxConseilerAvResult.setItemText(1, _translate("MainWindow", "Non"))
        self.label_26.setText(_translate("MainWindow", "Conseiller et dépister ayant reçu son résultat :"))
        self.comboBoxResultat.setItemText(0, _translate("MainWindow", "Négatif"))
        self.comboBoxResultat.setItemText(1, _translate("MainWindow", "Positif"))
        self.comboBoxResultat.setItemText(2, _translate("MainWindow", "Indéterminé"))
        self.comboBoxResultat.setItemText(3, _translate("MainWindow", "Statut connu"))
        self.label_27.setText(_translate("MainWindow", "Résultat du test de dépistage : "))
        self.comboBoxPositifConnaisResultat.setItemText(0, _translate("MainWindow", "Oui"))
        self.comboBoxPositifConnaisResultat.setItemText(1, _translate("MainWindow", "Non"))
        self.label_28.setText(_translate("MainWindow", "Positif ayant reçu son résultat :"))
        self.label_29.setText(_translate("MainWindow", "Positif bénéficiant d\'un CD4 :"))
        self.comboBoxBeneficiantCD4.setItemText(0, _translate("MainWindow", "Oui"))
        self.comboBoxBeneficiantCD4.setItemText(1, _translate("MainWindow", "Non"))
        self.pushButtonEnregistrer.setText(_translate("MainWindow", "Enregistrer"))
        self.pushButtonAnnuler2.setText(_translate("MainWindow", "Annuler"))
        self.tableWidgetData.setSortingEnabled(False)
        item = self.tableWidgetData.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date de dépistage"))
        item = self.tableWidgetData.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Poste de dépistage"))
        item = self.tableWidgetData.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Code du patient"))
        item = self.tableWidgetData.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Sexe du patient"))
        item = self.tableWidgetData.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Tranche d\'age"))
        item = self.tableWidgetData.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Conseiller pour le test"))
        item = self.tableWidgetData.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Effectivement dépisté"))
        item = self.tableWidgetData.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "CD ayant reçu son résultat"))
        item = self.tableWidgetData.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Résultat du test"))
        item = self.tableWidgetData.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Positif ayant reçu son résultat"))
        item = self.tableWidgetData.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Positif bénéficiant d\'un CD4"))
        __sortingEnabled = self.tableWidgetData.isSortingEnabled()
        self.tableWidgetData.setSortingEnabled(False)
        self.tableWidgetData.setSortingEnabled(__sortingEnabled)
        self.label_10.setText(_translate("MainWindow", "Les données exporter sont celles de la periode selectionnée"))
        self.labelExtration_2.setText(_translate("MainWindow", "Exportation "))
        self.pushButtonExporter2.setText(_translate("MainWindow", "Exporter"))
        self.label_7.setText(_translate("MainWindow", "Entrer le nom du dossier de sauvegarde"))
        self.labelExt1_2.setText(_translate("MainWindow", "Exporter les fichiesr excels (*.xlsx, *.xls)."))
        self.labelLogo3.setText(_translate("MainWindow", "ing"))
        self.labelLogo5.setText(_translate("MainWindow", "ool"))
        self.labelLogo2.setText(_translate("MainWindow", "T"))
        self.labelLogo1.setText(_translate("MainWindow", "Repor"))
        self.pushButtonEnregistrement.setText(_translate("MainWindow", "     Enregistrement"))
        self.pushButtonAccueil.setText(_translate("MainWindow", "     Accueil"))
        self.pushButtonVisualisation.setText(_translate("MainWindow", "     Visualisation"))
        self.pushButtonExporter.setText(_translate("MainWindow", "     Exporter"))
        self.pushButtonDonnees.setText(_translate("MainWindow", "     Données"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

