# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_FData.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 1000)
        MainWindow.setMinimumSize(QtCore.QSize(1194, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 1000))
        MainWindow.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(206, 0, 991, 71))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"/*border: 1px solid ;*/")
        self.label.setText("")
        self.label.setObjectName("label")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(209, 200, 991, 811))
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageExtraction = QtWidgets.QWidget()
        self.pageExtraction.setObjectName("pageExtraction")
        self.label_17 = QtWidgets.QLabel(self.pageExtraction)
        self.label_17.setGeometry(QtCore.QRect(100, 100, 681, 431))
        self.label_17.setStyleSheet("border: 0.5px solid ;\n"
"background-color: rgb(255, 255, 255);")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.pushButtonExporter2 = QtWidgets.QPushButton(self.pageExtraction)
        self.pushButtonExporter2.setGeometry(QtCore.QRect(630, 310, 85, 30))
        self.pushButtonExporter2.setStyleSheet("background-color: rgb(6, 88, 47);\n"
"color: rgb(255, 255, 255);")
        self.pushButtonExporter2.setObjectName("pushButtonExporter2")
        self.labelExtration_2 = QtWidgets.QLabel(self.pageExtraction)
        self.labelExtration_2.setGeometry(QtCore.QRect(260, 140, 131, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.labelExtration_2.setFont(font)
        self.labelExtration_2.setStyleSheet("color: rgb(6, 88, 47);\n"
"font-weight: bold;\n"
"font-size:16px;\n"
"font-style : normal ;")
        self.labelExtration_2.setObjectName("labelExtration_2")
        self.lineExt_2 = QtWidgets.QFrame(self.pageExtraction)
        self.lineExt_2.setGeometry(QtCore.QRect(240, 140, 3, 50))
        self.lineExt_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.lineExt_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineExt_2.setObjectName("lineExt_2")
        self.labelExt1_2 = QtWidgets.QLabel(self.pageExtraction)
        self.labelExt1_2.setGeometry(QtCore.QRect(260, 170, 361, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.labelExt1_2.setFont(font)
        self.labelExt1_2.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"font-style : italic ;")
        self.labelExt1_2.setObjectName("labelExt1_2")
        self.lineEditExporter = QtWidgets.QLineEdit(self.pageExtraction)
        self.lineEditExporter.setGeometry(QtCore.QRect(152, 310, 441, 25))
        self.lineEditExporter.setObjectName("lineEditExporter")
        self.label_15 = QtWidgets.QLabel(self.pageExtraction)
        self.label_15.setGeometry(QtCore.QRect(103, 101, 681, 431))
        self.label_15.setStyleSheet("border: 0.5px solid ;\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.pageExtraction)
        self.label_16.setGeometry(QtCore.QRect(160, 130, 71, 61))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("images/yesterday1.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_7 = QtWidgets.QLabel(self.pageExtraction)
        self.label_7.setGeometry(QtCore.QRect(150, 280, 301, 21))
        self.label_7.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"font-style : italic ;\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.pageExtraction)
        self.label_8.setGeometry(QtCore.QRect(200, 390, 491, 61))
        self.label_8.setStyleSheet("border: 1px solid black ;")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.pageExtraction)
        self.label_9.setGeometry(QtCore.QRect(210, 400, 51, 41))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("images/info.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.pageExtraction)
        self.label_10.setGeometry(QtCore.QRect(270, 410, 401, 20))
        self.label_10.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"font-style : italic ;\n"
"")
        self.label_10.setObjectName("label_10")
        self.label_15.raise_()
        self.label_17.raise_()
        self.labelExtration_2.raise_()
        self.lineExt_2.raise_()
        self.labelExt1_2.raise_()
        self.lineEditExporter.raise_()
        self.label_16.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.pushButtonExporter2.raise_()
        self.stackedWidget.addWidget(self.pageExtraction)
        self.pageView = QtWidgets.QWidget()
        self.pageView.setObjectName("pageView")
        self.tableWidgetData = QtWidgets.QTableWidget(self.pageView)
        self.tableWidgetData.setGeometry(QtCore.QRect(10, 30, 975, 731))
        self.tableWidgetData.setAlternatingRowColors(True)
        self.tableWidgetData.setRowCount(31)
        self.tableWidgetData.setObjectName("tableWidgetData")
        self.tableWidgetData.setColumnCount(11)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetData.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetData.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetData.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetData.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetData.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetData.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetData.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetData.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetData.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetData.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetData.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetData.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetData.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetData.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetData.setItem(1, 1, item)
        self.tableWidgetData.verticalHeader().setVisible(False)
        self.stackedWidget.addWidget(self.pageView)
        self.pageGraph = QtWidgets.QWidget()
        self.pageGraph.setObjectName("pageGraph")
        self.scrollArea = QtWidgets.QScrollArea(self.pageGraph)
        self.scrollArea.setGeometry(QtCore.QRect(7, 10, 967, 771))
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 965, 769))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.graphicsView1 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.graphicsView1.setGeometry(QtCore.QRect(10, 10, 471, 371))
        self.graphicsView1.setObjectName("graphicsView1")
        self.graphicsView2 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.graphicsView2.setGeometry(QtCore.QRect(490, 10, 471, 371))
        self.graphicsView2.setObjectName("graphicsView2")
        self.graphicsView3 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.graphicsView3.setGeometry(QtCore.QRect(10, 390, 471, 371))
        self.graphicsView3.setObjectName("graphicsView3")
        self.graphicsView4 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.graphicsView4.setGeometry(QtCore.QRect(490, 390, 471, 371))
        self.graphicsView4.setObjectName("graphicsView4")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.stackedWidget.addWidget(self.pageGraph)
        self.pageAccueil = QtWidgets.QWidget()
        self.pageAccueil.setObjectName("pageAccueil")
        self.label_12 = QtWidgets.QLabel(self.pageAccueil)
        self.label_12.setGeometry(QtCore.QRect(160, 190, 681, 431))
        self.label_12.setStyleSheet("border: 0.5px solid ;\n"
"background-color: rgb(255, 255, 255);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.pageAccueil)
        self.label_13.setGeometry(QtCore.QRect(220, 220, 71, 61))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("images/database.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.lineEditImporterFichier = QtWidgets.QLineEdit(self.pageAccueil)
        self.lineEditImporterFichier.setGeometry(QtCore.QRect(212, 380, 441, 25))
        self.lineEditImporterFichier.setObjectName("lineEditImporterFichier")
        self.pushButtonAnnuler = QtWidgets.QPushButton(self.pageAccueil)
        self.pushButtonAnnuler.setGeometry(QtCore.QRect(354, 440, 85, 30))
        self.pushButtonAnnuler.setStyleSheet("background-color: rgb(6, 88, 47);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.pushButtonAnnuler.setObjectName("pushButtonAnnuler")
        self.pushButtonOK = QtWidgets.QPushButton(self.pageAccueil)
        self.pushButtonOK.setGeometry(QtCore.QRect(474, 440, 85, 30))
        self.pushButtonOK.setStyleSheet("background-color: rgb(6, 88, 47);\n"
"color: rgb(255, 255, 255);")
        self.pushButtonOK.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.pushButtonFichier = QtWidgets.QPushButton(self.pageAccueil)
        self.pushButtonFichier.setGeometry(QtCore.QRect(690, 380, 85, 30))
        self.pushButtonFichier.setStyleSheet("background-color: rgb(6, 88, 47);\n"
"color: rgb(255, 255, 255);")
        self.pushButtonFichier.setObjectName("pushButtonFichier")
        self.label_14 = QtWidgets.QLabel(self.pageAccueil)
        self.label_14.setGeometry(QtCore.QRect(163, 191, 681, 431))
        self.label_14.setStyleSheet("border: 0.5px solid ;\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.labelExt1 = QtWidgets.QLabel(self.pageAccueil)
        self.labelExt1.setGeometry(QtCore.QRect(320, 260, 361, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.labelExt1.setFont(font)
        self.labelExt1.setStyleSheet("font-style : italic ;")
        self.labelExt1.setObjectName("labelExt1")
        self.lineExt = QtWidgets.QFrame(self.pageAccueil)
        self.lineExt.setGeometry(QtCore.QRect(300, 230, 3, 50))
        self.lineExt.setFrameShape(QtWidgets.QFrame.VLine)
        self.lineExt.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineExt.setObjectName("lineExt")
        self.labelExtration = QtWidgets.QLabel(self.pageAccueil)
        self.labelExtration.setGeometry(QtCore.QRect(320, 230, 131, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.labelExtration.setFont(font)
        self.labelExtration.setStyleSheet("color: rgb(6, 88, 47);\n"
"font-weight: bold;\n"
"font-size:16px;\n"
"font-style : normal ;")
        self.labelExtration.setObjectName("labelExtration")
        self.label_14.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.lineEditImporterFichier.raise_()
        self.pushButtonAnnuler.raise_()
        self.pushButtonOK.raise_()
        self.pushButtonFichier.raise_()
        self.labelExt1.raise_()
        self.lineExt.raise_()
        self.labelExtration.raise_()
        self.stackedWidget.addWidget(self.pageAccueil)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.groupBoxGenerale = QtWidgets.QGroupBox(self.page)
        self.groupBoxGenerale.setGeometry(QtCore.QRect(130, 60, 751, 141))
        self.groupBoxGenerale.setStyleSheet("color:  rgb(6, 88, 47);\n"
"border: 1px solid;\n"
"border-color: rgb(6, 88, 47);\n"
"color:  rgb(6, 88, 47);")
        self.groupBoxGenerale.setObjectName("groupBoxGenerale")
        self.comboBoxPosteEnreg = QtWidgets.QComboBox(self.groupBoxGenerale)
        self.comboBoxPosteEnreg.setGeometry(QtCore.QRect(210, 40, 311, 22))
        self.comboBoxPosteEnreg.setObjectName("comboBoxPosteEnreg")
        self.comboBoxPosteEnreg.addItem("")
        self.comboBoxPosteEnreg.addItem("")
        self.comboBoxPosteEnreg.addItem("")
        self.comboBoxPosteEnreg.addItem("")
        self.comboBoxPosteEnreg.addItem("")
        self.comboBoxPosteEnreg.addItem("")
        self.comboBoxPosteEnreg.addItem("")
        self.comboBoxPosteEnreg.addItem("")
        self.label_11 = QtWidgets.QLabel(self.groupBoxGenerale)
        self.label_11.setGeometry(QtCore.QRect(20, 40, 151, 16))
        self.label_11.setStyleSheet("border: 0px solid;")
        self.label_11.setObjectName("label_11")
        self.dateEditDateEnreg = QtWidgets.QDateEdit(self.groupBoxGenerale)
        self.dateEditDateEnreg.setGeometry(QtCore.QRect(190, 87, 121, 22))
        self.dateEditDateEnreg.setCalendarPopup(True)
        self.dateEditDateEnreg.setObjectName("dateEditDateEnreg")
        self.label_18 = QtWidgets.QLabel(self.groupBoxGenerale)
        self.label_18.setGeometry(QtCore.QRect(30, 90, 141, 16))
        self.label_18.setStyleSheet("border: 0px solid;")
        self.label_18.setObjectName("label_18")
        self.pushButtonEnregistrer = QtWidgets.QPushButton(self.groupBoxGenerale)
        self.pushButtonEnregistrer.setGeometry(QtCore.QRect(630, 20, 101, 31))
        self.pushButtonEnregistrer.setStyleSheet("background-color: rgb(6, 88, 47);\n"
"color: rgb(255, 255, 255);")
        self.pushButtonEnregistrer.setObjectName("pushButtonEnregistrer")
        self.groupBoxPatient = QtWidgets.QGroupBox(self.page)
        self.groupBoxPatient.setGeometry(QtCore.QRect(120, 220, 751, 231))
        self.groupBoxPatient.setStyleSheet("color:  rgb(6, 88, 47);\n"
"border: 1px solid;\n"
"border-color: rgb(6, 88, 47);\n"
"")
        self.groupBoxPatient.setObjectName("groupBoxPatient")
        self.lineEditCodePatient = QtWidgets.QLineEdit(self.groupBoxPatient)
        self.lineEditCodePatient.setGeometry(QtCore.QRect(220, 30, 241, 20))
        self.lineEditCodePatient.setObjectName("lineEditCodePatient")
        self.label_19 = QtWidgets.QLabel(self.groupBoxPatient)
        self.label_19.setGeometry(QtCore.QRect(70, 30, 131, 16))
        self.label_19.setStyleSheet("border: 0px solid;")
        self.label_19.setObjectName("label_19")
        self.comboBoxSexeEnreg = QtWidgets.QComboBox(self.groupBoxPatient)
        self.comboBoxSexeEnreg.setGeometry(QtCore.QRect(220, 70, 101, 22))
        self.comboBoxSexeEnreg.setObjectName("comboBoxSexeEnreg")
        self.comboBoxSexeEnreg.addItem("")
        self.comboBoxSexeEnreg.addItem("")
        self.label_20 = QtWidgets.QLabel(self.groupBoxPatient)
        self.label_20.setGeometry(QtCore.QRect(150, 70, 51, 20))
        self.label_20.setStyleSheet("border: 0px solid;")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBoxPatient)
        self.label_21.setGeometry(QtCore.QRect(150, 120, 47, 21))
        self.label_21.setStyleSheet("border: 0px solid;")
        self.label_21.setObjectName("label_21")
        self.spinBoxAge = QtWidgets.QSpinBox(self.groupBoxPatient)
        self.spinBoxAge.setGeometry(QtCore.QRect(220, 120, 61, 22))
        self.spinBoxAge.setPrefix("")
        self.spinBoxAge.setMinimum(1)
        self.spinBoxAge.setProperty("value", 1)
        self.spinBoxAge.setObjectName("spinBoxAge")
        self.comboBoxGandeur = QtWidgets.QComboBox(self.groupBoxPatient)
        self.comboBoxGandeur.setGeometry(QtCore.QRect(480, 120, 121, 22))
        self.comboBoxGandeur.setObjectName("comboBoxGandeur")
        self.comboBoxGandeur.addItem("")
        self.comboBoxGandeur.addItem("")
        self.comboBoxGandeur.addItem("")
        self.comboBoxGandeur.addItem("")
        self.label_23 = QtWidgets.QLabel(self.groupBoxPatient)
        self.label_23.setGeometry(QtCore.QRect(320, 120, 141, 21))
        self.label_23.setStyleSheet("\n"
"border: 0px solid;")
        self.label_23.setObjectName("label_23")
        self.comboBoxTrancheAge = QtWidgets.QComboBox(self.groupBoxPatient)
        self.comboBoxTrancheAge.setGeometry(QtCore.QRect(220, 170, 141, 22))
        self.comboBoxTrancheAge.setEditable(False)
        self.comboBoxTrancheAge.setDuplicatesEnabled(False)
        self.comboBoxTrancheAge.setObjectName("comboBoxTrancheAge")
        self.comboBoxTrancheAge.addItem("")
        self.comboBoxTrancheAge.addItem("")
        self.comboBoxTrancheAge.addItem("")
        self.comboBoxTrancheAge.addItem("")
        self.comboBoxTrancheAge.addItem("")
        self.comboBoxTrancheAge.addItem("")
        self.comboBoxTrancheAge.addItem("")
        self.comboBoxTrancheAge.addItem("")
        self.comboBoxTrancheAge.addItem("")
        self.comboBoxTrancheAge.addItem("")
        self.label_22 = QtWidgets.QLabel(self.groupBoxPatient)
        self.label_22.setGeometry(QtCore.QRect(10, 170, 191, 16))
        self.label_22.setStyleSheet("border: 0px solid;")
        self.label_22.setObjectName("label_22")
        self.groupBoxDepistage = QtWidgets.QGroupBox(self.page)
        self.groupBoxDepistage.setGeometry(QtCore.QRect(120, 470, 751, 221))
        self.groupBoxDepistage.setStyleSheet("color:  rgb(6, 88, 47);\n"
"border: 1px solid;\n"
"border-color: rgb(6, 88, 47);\n"
"color:  rgb(6, 88, 47);")
        self.groupBoxDepistage.setCheckable(False)
        self.groupBoxDepistage.setObjectName("groupBoxDepistage")
        self.comboBoxConseilDep = QtWidgets.QComboBox(self.groupBoxDepistage)
        self.comboBoxConseilDep.setGeometry(QtCore.QRect(190, 30, 69, 22))
        self.comboBoxConseilDep.setObjectName("comboBoxConseilDep")
        self.comboBoxConseilDep.addItem("")
        self.comboBoxConseilDep.addItem("")
        self.label_24 = QtWidgets.QLabel(self.groupBoxDepistage)
        self.label_24.setGeometry(QtCore.QRect(10, 30, 171, 21))
        self.label_24.setStyleSheet("border: 0px solid;")
        self.label_24.setObjectName("label_24")
        self.comboBoxEffectDep = QtWidgets.QComboBox(self.groupBoxDepistage)
        self.comboBoxEffectDep.setGeometry(QtCore.QRect(610, 30, 69, 22))
        self.comboBoxEffectDep.setObjectName("comboBoxEffectDep")
        self.comboBoxEffectDep.addItem("")
        self.comboBoxEffectDep.addItem("")
        self.label_25 = QtWidgets.QLabel(self.groupBoxDepistage)
        self.label_25.setGeometry(QtCore.QRect(430, 30, 171, 16))
        self.label_25.setStyleSheet("border: 0px solid;")
        self.label_25.setObjectName("label_25")
        self.comboBoxConseilerAvResult = QtWidgets.QComboBox(self.groupBoxDepistage)
        self.comboBoxConseilerAvResult.setGeometry(QtCore.QRect(350, 80, 69, 22))
        self.comboBoxConseilerAvResult.setObjectName("comboBoxConseilerAvResult")
        self.comboBoxConseilerAvResult.addItem("")
        self.comboBoxConseilerAvResult.addItem("")
        self.label_26 = QtWidgets.QLabel(self.groupBoxDepistage)
        self.label_26.setGeometry(QtCore.QRect(10, 80, 331, 16))
        self.label_26.setStyleSheet("border: 0px solid;")
        self.label_26.setObjectName("label_26")
        self.comboBoxResultat = QtWidgets.QComboBox(self.groupBoxDepistage)
        self.comboBoxResultat.setGeometry(QtCore.QRect(240, 130, 121, 22))
        self.comboBoxResultat.setObjectName("comboBoxResultat")
        self.comboBoxResultat.addItem("")
        self.comboBoxResultat.addItem("")
        self.comboBoxResultat.addItem("")
        self.comboBoxResultat.addItem("")
        self.label_27 = QtWidgets.QLabel(self.groupBoxDepistage)
        self.label_27.setGeometry(QtCore.QRect(10, 130, 221, 16))
        self.label_27.setStyleSheet("border: 0px solid;")
        self.label_27.setObjectName("label_27")
        self.comboBoxPositifConnaisResultat = QtWidgets.QComboBox(self.groupBoxDepistage)
        self.comboBoxPositifConnaisResultat.setGeometry(QtCore.QRect(640, 130, 69, 22))
        self.comboBoxPositifConnaisResultat.setObjectName("comboBoxPositifConnaisResultat")
        self.comboBoxPositifConnaisResultat.addItem("")
        self.comboBoxPositifConnaisResultat.addItem("")
        self.label_28 = QtWidgets.QLabel(self.groupBoxDepistage)
        self.label_28.setGeometry(QtCore.QRect(410, 130, 231, 20))
        self.label_28.setStyleSheet("border: 0px solid;")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBoxDepistage)
        self.label_29.setGeometry(QtCore.QRect(10, 180, 211, 16))
        self.label_29.setStyleSheet("border: 0px solid;")
        self.label_29.setObjectName("label_29")
        self.comboBoxBeneficiantCD4 = QtWidgets.QComboBox(self.groupBoxDepistage)
        self.comboBoxBeneficiantCD4.setGeometry(QtCore.QRect(240, 180, 69, 20))
        self.comboBoxBeneficiantCD4.setObjectName("comboBoxBeneficiantCD4")
        self.comboBoxBeneficiantCD4.addItem("")
        self.comboBoxBeneficiantCD4.addItem("")
        self.pushButtonAnnuler2 = QtWidgets.QPushButton(self.page)
        self.pushButtonAnnuler2.setGeometry(QtCore.QRect(580, 710, 101, 31))
        self.pushButtonAnnuler2.setStyleSheet("background-color: rgb(6, 88, 47);\n"
"color: rgb(255, 255, 255);")
        self.pushButtonAnnuler2.setObjectName("pushButtonAnnuler2")
        self.label_30 = QtWidgets.QLabel(self.page)
        self.label_30.setGeometry(QtCore.QRect(80, 20, 831, 741))
        self.label_30.setStyleSheet("background-color: rgb(6, 88, 47);")
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.page)
        self.label_31.setGeometry(QtCore.QRect(90, 30, 811, 721))
        self.label_31.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.label_30.raise_()
        self.label_31.raise_()
        self.groupBoxGenerale.raise_()
        self.groupBoxPatient.raise_()
        self.groupBoxDepistage.raise_()
        self.pushButtonAnnuler2.raise_()
        self.stackedWidget.addWidget(self.page)
        self.groupBoxFiltre = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxFiltre.setGeometry(QtCore.QRect(810, 90, 371, 101))
        self.groupBoxFiltre.setObjectName("groupBoxFiltre")
        self.label_6 = QtWidgets.QLabel(self.groupBoxFiltre)
        self.label_6.setGeometry(QtCore.QRect(20, 26, 47, 13))
        self.label_6.setObjectName("label_6")
        self.comboBoxSexe = QtWidgets.QComboBox(self.groupBoxFiltre)
        self.comboBoxSexe.setGeometry(QtCore.QRect(20, 47, 91, 22))
        self.comboBoxSexe.setObjectName("comboBoxSexe")
        self.comboBoxSexe.addItem("")
        self.comboBoxSexe.addItem("")
        self.comboBoxSexe.addItem("")
        self.label_3 = QtWidgets.QLabel(self.groupBoxFiltre)
        self.label_3.setGeometry(QtCore.QRect(180, 26, 127, 16))
        self.label_3.setObjectName("label_3")
        self.comboBoxPoste = QtWidgets.QComboBox(self.groupBoxFiltre)
        self.comboBoxPoste.setGeometry(QtCore.QRect(180, 45, 151, 22))
        self.comboBoxPoste.setObjectName("comboBoxPoste")
        self.pushButtonOkFiltre = QtWidgets.QPushButton(self.groupBoxFiltre)
        self.pushButtonOkFiltre.setGeometry(QtCore.QRect(257, 70, 75, 23))
        self.pushButtonOkFiltre.setObjectName("pushButtonOkFiltre")
        self.radioButtonFiltre = QtWidgets.QRadioButton(self.groupBoxFiltre)
        self.radioButtonFiltre.setGeometry(QtCore.QRect(22, 78, 171, 17))
        self.radioButtonFiltre.setObjectName("radioButtonFiltre")
        self.groupBoxPeriode = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxPeriode.setEnabled(True)
        self.groupBoxPeriode.setGeometry(QtCore.QRect(330, 90, 461, 101))
        self.groupBoxPeriode.setObjectName("groupBoxPeriode")
        self.dateEditDebut = QtWidgets.QDateEdit(self.groupBoxPeriode)
        self.dateEditDebut.setGeometry(QtCore.QRect(80, 36, 110, 22))
        self.dateEditDebut.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1752, 10, 1), QtCore.QTime(0, 0, 0)))
        self.dateEditDebut.setMinimumDate(QtCore.QDate(1752, 10, 1))
        self.dateEditDebut.setCalendarPopup(True)
        self.dateEditDebut.setDate(QtCore.QDate(2020, 1, 1))
        self.dateEditDebut.setObjectName("dateEditDebut")
        self.label_4 = QtWidgets.QLabel(self.groupBoxPeriode)
        self.label_4.setGeometry(QtCore.QRect(20, 40, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBoxPeriode)
        self.label_5.setGeometry(QtCore.QRect(270, 40, 47, 13))
        self.label_5.setObjectName("label_5")
        self.dateEditFin = QtWidgets.QDateEdit(self.groupBoxPeriode)
        self.dateEditFin.setGeometry(QtCore.QRect(311, 36, 110, 22))
        self.dateEditFin.setMaximumDate(QtCore.QDate(2099, 1, 1))
        self.dateEditFin.setCalendarPopup(True)
        self.dateEditFin.setDate(QtCore.QDate(2020, 3, 1))
        self.dateEditFin.setObjectName("dateEditFin")
        self.radioButtonAll = QtWidgets.QRadioButton(self.groupBoxPeriode)
        self.radioButtonAll.setGeometry(QtCore.QRect(20, 70, 111, 20))
        self.radioButtonAll.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.radioButtonAll.setIconSize(QtCore.QSize(16, 16))
        self.radioButtonAll.setChecked(False)
        self.radioButtonAll.setObjectName("radioButtonAll")
        self.pushButtonOkPeriode = QtWidgets.QPushButton(self.groupBoxPeriode)
        self.pushButtonOkPeriode.setGeometry(QtCore.QRect(350, 70, 75, 23))
        self.pushButtonOkPeriode.setObjectName("pushButtonOkPeriode")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 70, 991, 131))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.labelMinstSante = QtWidgets.QLabel(self.centralwidget)
        self.labelMinstSante.setGeometry(QtCore.QRect(1120, 10, 61, 51))
        self.labelMinstSante.setText("")
        self.labelMinstSante.setPixmap(QtGui.QPixmap("images/téléchargement.png"))
        self.labelMinstSante.setScaledContents(True)
        self.labelMinstSante.setObjectName("labelMinstSante")
        self.labelDCDJ = QtWidgets.QLabel(self.centralwidget)
        self.labelDCDJ.setGeometry(QtCore.QRect(970, 10, 141, 51))
        self.labelDCDJ.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelDCDJ.setText("")
        self.labelDCDJ.setPixmap(QtGui.QPixmap("images/DCDJ_logo_0.png"))
        self.labelDCDJ.setScaledContents(True)
        self.labelDCDJ.setObjectName("labelDCDJ")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(210, 61, 991, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, -8, 1200, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.line_3.setFont(font)
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.labelAppName = QtWidgets.QLabel(self.centralwidget)
        self.labelAppName.setGeometry(QtCore.QRect(250, 10, 411, 51))
        self.labelAppName.setStyleSheet("font: 30pt \"MV Boli\";\n"
"color: rgb(6, 88, 47);")
        self.labelAppName.setObjectName("labelAppName")
        self.labelMenu = QtWidgets.QLabel(self.centralwidget)
        self.labelMenu.setGeometry(QtCore.QRect(0, 0, 211, 1001))
        self.labelMenu.setStyleSheet("\n"
"background-color: rgb(6, 88, 47);")
        self.labelMenu.setText("")
        self.labelMenu.setObjectName("labelMenu")
        self.pushButtonDonnees = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDonnees.setGeometry(QtCore.QRect(0, 380, 210, 40))
        self.pushButtonDonnees.setStyleSheet("QPushButton{background-color: rgb(6, 88, 47); font: 87 12pt \"Segoe UI Black\"; color: rgb(255, 255, 255); font-weight: bold; text-align: left; border: 0px solid; font-style : italic ; } QPushButton:hover{ background-color: rgb(19, 252, 136); background-color: rgb(5, 75, 40); border-left: 5px solid; border-left-color: rgb(85, 255, 0);}")
        self.pushButtonDonnees.setFlat(True)
        self.pushButtonDonnees.setObjectName("pushButtonDonnees")
        self.pushButtonEnregistrement = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonEnregistrement.setGeometry(QtCore.QRect(0, 340, 210, 40))
        self.pushButtonEnregistrement.setStyleSheet("QPushButton{\n"
"    background-color: rgb(6, 88, 47);\n"
"    font: 87 12pt \"Segoe UI Black\";\n"
"    color: rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"    text-align: left;\n"
"    border: 0px solid;\n"
"    font-style : italic ;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(5, 75, 40);\n"
"    border-left: 5px solid;\n"
"    border-left-color: rgb(85, 255, 0);\n"
"}")
        self.pushButtonEnregistrement.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonEnregistrement.setFlat(True)
        self.pushButtonEnregistrement.setObjectName("pushButtonEnregistrement")
        self.pushButtonVisualisation = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonVisualisation.setGeometry(QtCore.QRect(0, 420, 210, 40))
        self.pushButtonVisualisation.setStyleSheet("QPushButton{\n"
"    background-color: rgb(6, 88, 47);\n"
"    font: 87 12pt \"Segoe UI Black\";\n"
"    color: rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"    text-align: left;\n"
"    border: 0px solid;\n"
"    font-style : italic ;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(5, 75, 40);\n"
"    border-left: 5px solid;\n"
"    border-left-color: rgb(85, 255, 0);\n"
"}")
        self.pushButtonVisualisation.setFlat(True)
        self.pushButtonVisualisation.setObjectName("pushButtonVisualisation")
        self.labelDCDJ2 = QtWidgets.QLabel(self.centralwidget)
        self.labelDCDJ2.setGeometry(QtCore.QRect(10, 920, 181, 51))
        self.labelDCDJ2.setStyleSheet("background-color: rgb(6, 88, 47);")
        self.labelDCDJ2.setText("")
        self.labelDCDJ2.setPixmap(QtGui.QPixmap("images/DCDJ_logo_0.png"))
        self.labelDCDJ2.setScaledContents(True)
        self.labelDCDJ2.setObjectName("labelDCDJ2")
        self.pushButtonAccueil = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAccueil.setGeometry(QtCore.QRect(0, 300, 210, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButtonAccueil.setFont(font)
        self.pushButtonAccueil.setAcceptDrops(False)
        self.pushButtonAccueil.setAutoFillBackground(False)
        self.pushButtonAccueil.setStyleSheet("QPushButton{\n"
"    background-color: rgb(6, 88, 47);\n"
"    font: 87 12pt \"Segoe UI Black\";\n"
"    color: rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"    text-align: left;\n"
"    border: 0px solid;\n"
"    font-style : italic ;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(5, 75, 40);\n"
"    \n"
"    border-left: 5px solid;\n"
"    border-left-color: rgb(85, 255, 0);\n"
"}")
        self.pushButtonAccueil.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonAccueil.setCheckable(False)
        self.pushButtonAccueil.setChecked(False)
        self.pushButtonAccueil.setAutoRepeat(False)
        self.pushButtonAccueil.setAutoExclusive(False)
        self.pushButtonAccueil.setAutoDefault(False)
        self.pushButtonAccueil.setDefault(False)
        self.pushButtonAccueil.setFlat(False)
        self.pushButtonAccueil.setObjectName("pushButtonAccueil")
        self.labelLogo1 = QtWidgets.QLabel(self.centralwidget)
        self.labelLogo1.setGeometry(QtCore.QRect(20, 40, 71, 41))
        self.labelLogo1.setStyleSheet("font: 18pt \"MV Boli\";\n"
"color: rgb(255, 85, 0);")
        self.labelLogo1.setObjectName("labelLogo1")
        self.labelLogo2 = QtWidgets.QLabel(self.centralwidget)
        self.labelLogo2.setGeometry(QtCore.QRect(60, 30, 81, 81))
        self.labelLogo2.setStyleSheet("font: 60pt \"MV Boli\";\n"
"color: rgb(255, 255, 255);")
        self.labelLogo2.setObjectName("labelLogo2")
        self.labelLogo3 = QtWidgets.QLabel(self.centralwidget)
        self.labelLogo3.setGeometry(QtCore.QRect(105, 46, 53, 31))
        self.labelLogo3.setStyleSheet("font: 18pt \"MV Boli\";\n"
"color: rgb(255, 85, 0);")
        self.labelLogo3.setObjectName("labelLogo3")
        self.labelLogo5 = QtWidgets.QLabel(self.centralwidget)
        self.labelLogo5.setGeometry(QtCore.QRect(100, 73, 47, 31))
        self.labelLogo5.setStyleSheet("font: 16pt \"MV Boli\";\n"
"color: rgb(255, 255, 255);")
        self.labelLogo5.setObjectName("labelLogo5")
        self.labelLogo4 = QtWidgets.QLabel(self.centralwidget)
        self.labelLogo4.setGeometry(QtCore.QRect(40, 70, 41, 31))
        self.labelLogo4.setText("")
        self.labelLogo4.setPixmap(QtGui.QPixmap("images/upload1 (2).png"))
        self.labelLogo4.setScaledContents(True)
        self.labelLogo4.setObjectName("labelLogo4")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(210, 202, 981, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.labelAuthor58168122 = QtWidgets.QLabel(self.centralwidget)
        self.labelAuthor58168122.setGeometry(QtCore.QRect(1084, 980, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelAuthor58168122.setFont(font)
        self.labelAuthor58168122.setStyleSheet("font: italic 8pt \"Arial Narrow\";\n"
"font-size:9px;\n"
"font-weight: bold;\n"
"")
        self.labelAuthor58168122.setObjectName("labelAuthor58168122")
        self.pushButtonExporter = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonExporter.setGeometry(QtCore.QRect(0, 460, 210, 40))
        self.pushButtonExporter.setStyleSheet("QPushButton{\n"
"    background-color: rgb(6, 88, 47);\n"
"    font: 87 12pt \"Segoe UI Black\";\n"
"    color: rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"    text-align: left;\n"
"    border: 0px solid;\n"
"    font-style : italic ;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(5, 75, 40);\n"
"    border-left: 5px solid;\n"
"    border-left-color: rgb(85, 255, 0);\n"
"}")
        self.pushButtonExporter.setFlat(True)
        self.pushButtonExporter.setObjectName("pushButtonExporter")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(220, 110, 51, 16))
        self.label_32.setObjectName("label_32")
        self.comboBoxSource = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxSource.setGeometry(QtCore.QRect(220, 130, 101, 31))
        self.comboBoxSource.setObjectName("comboBoxSource")
        self.comboBoxSource.addItem("")
        self.comboBoxSource.addItem("")
        self.labelEnregistrement = QtWidgets.QLabel(self.centralwidget)
        self.labelEnregistrement.setEnabled(False)
        self.labelEnregistrement.setGeometry(QtCore.QRect(220, 80, 961, 121))
        self.labelEnregistrement.setStyleSheet("font: 20pt \"MV Boli\";\n"
"color: rgb(6, 88, 47);\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.labelEnregistrement.setText("")
        self.labelEnregistrement.setObjectName("labelEnregistrement")
        self.labelEnregiestrement = QtWidgets.QLabel(self.centralwidget)
        self.labelEnregiestrement.setGeometry(QtCore.QRect(490, 80, 371, 121))
        self.labelEnregiestrement.setStyleSheet("font: 20pt \"MV Boli\";\n"
"color: rgb(6, 88, 47);\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.labelEnregiestrement.setObjectName("labelEnregiestrement")
        self.stackedWidget.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.labelMenu.raise_()
        self.labelMinstSante.raise_()
        self.labelDCDJ.raise_()
        self.groupBoxFiltre.raise_()
        self.groupBoxPeriode.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.labelAppName.raise_()
        self.pushButtonDonnees.raise_()
        self.pushButtonVisualisation.raise_()
        self.labelDCDJ2.raise_()
        self.pushButtonAccueil.raise_()
        self.pushButtonEnregistrement.raise_()
        self.labelLogo1.raise_()
        self.labelLogo2.raise_()
        self.labelLogo3.raise_()
        self.labelLogo5.raise_()
        self.labelLogo4.raise_()
        self.line_4.raise_()
        self.labelAuthor58168122.raise_()
        self.pushButtonExporter.raise_()
        self.label_32.raise_()
        self.comboBoxSource.raise_()
        self.labelEnregistrement.raise_()
        self.labelEnregiestrement.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        self.comboBoxSexe.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonExporter2.setText(_translate("MainWindow", "Exporter"))
        self.labelExtration_2.setText(_translate("MainWindow", "Exportation "))
        self.labelExt1_2.setText(_translate("MainWindow", "Exporter les fichiesr excels (*.xlsx, *.xls)."))
        self.label_7.setText(_translate("MainWindow", "Entrer le nom du dossier de sauvegarde"))
        self.label_10.setText(_translate("MainWindow", "Les données exporter sont celles de la periode selectionnée"))
        item = self.tableWidgetData.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date de dépistage"))
        item = self.tableWidgetData.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Poste de dépistage"))
        item = self.tableWidgetData.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Code du patient"))
        item = self.tableWidgetData.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Sexe du patient"))
        item = self.tableWidgetData.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Tranche d\'age"))
        item = self.tableWidgetData.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Conseiller pour le test"))
        item = self.tableWidgetData.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Effectivement dépisté"))
        item = self.tableWidgetData.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "CD ayant reçu son résultat"))
        item = self.tableWidgetData.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Résultat du test"))
        item = self.tableWidgetData.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Positif ayant reçu son résultat"))
        item = self.tableWidgetData.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Positif bénéficiant d\'un CD4"))
        __sortingEnabled = self.tableWidgetData.isSortingEnabled()
        self.tableWidgetData.setSortingEnabled(False)
        self.tableWidgetData.setSortingEnabled(__sortingEnabled)
        self.pushButtonAnnuler.setText(_translate("MainWindow", "annuler"))
        self.pushButtonOK.setText(_translate("MainWindow", "ok"))
        self.pushButtonFichier.setText(_translate("MainWindow", "Fichier"))
        self.labelExt1.setText(_translate("MainWindow", "Importer le fichier excel (*.xlsx, *.xls) à traiter."))
        self.labelExtration.setText(_translate("MainWindow", "Importation "))
        self.groupBoxGenerale.setTitle(_translate("MainWindow", "Générale"))
        self.comboBoxPosteEnreg.setItemText(0, _translate("MainWindow", "IST"))
        self.comboBoxPosteEnreg.setItemText(1, _translate("MainWindow", "Tuberculose"))
        self.comboBoxPosteEnreg.setItemText(2, _translate("MainWindow", "CPN2 et Plus + Accouch + CPoN"))
        self.comboBoxPosteEnreg.setItemText(3, _translate("MainWindow", "Hospitalisation"))
        self.comboBoxPosteEnreg.setItemText(4, _translate("MainWindow", "Index testing"))
        self.comboBoxPosteEnreg.setItemText(5, _translate("MainWindow", "Urgence"))
        self.comboBoxPosteEnreg.setItemText(6, _translate("MainWindow", "Malnutrition"))
        self.comboBoxPosteEnreg.setItemText(7, _translate("MainWindow", "AUTRE CDIP"))
        self.label_11.setText(_translate("MainWindow", "Poste de dépistage :"))
        self.dateEditDateEnreg.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.label_18.setText(_translate("MainWindow", "Date de dépistage :"))
        self.pushButtonEnregistrer.setText(_translate("MainWindow", "Enregistrer"))
        self.groupBoxPatient.setTitle(_translate("MainWindow", "Patient"))
        self.label_19.setText(_translate("MainWindow", "Code du patient :"))
        self.comboBoxSexeEnreg.setItemText(0, _translate("MainWindow", "Masculin"))
        self.comboBoxSexeEnreg.setItemText(1, _translate("MainWindow", "Feminin"))
        self.label_20.setText(_translate("MainWindow", "Sexe :"))
        self.label_21.setText(_translate("MainWindow", "Age :"))
        self.comboBoxGandeur.setItemText(0, _translate("MainWindow", "Années"))
        self.comboBoxGandeur.setItemText(1, _translate("MainWindow", "Mois"))
        self.comboBoxGandeur.setItemText(2, _translate("MainWindow", "Semaines"))
        self.comboBoxGandeur.setItemText(3, _translate("MainWindow", "Jours"))
        self.label_23.setText(_translate("MainWindow", "Grandeur de l\'age :"))
        self.comboBoxTrancheAge.setItemText(0, _translate("MainWindow", "0-4"))
        self.comboBoxTrancheAge.setItemText(1, _translate("MainWindow", "5-9"))
        self.comboBoxTrancheAge.setItemText(2, _translate("MainWindow", "10-14"))
        self.comboBoxTrancheAge.setItemText(3, _translate("MainWindow", "15-19"))
        self.comboBoxTrancheAge.setItemText(4, _translate("MainWindow", "20-24"))
        self.comboBoxTrancheAge.setItemText(5, _translate("MainWindow", "30-34"))
        self.comboBoxTrancheAge.setItemText(6, _translate("MainWindow", "35-39"))
        self.comboBoxTrancheAge.setItemText(7, _translate("MainWindow", "40-44"))
        self.comboBoxTrancheAge.setItemText(8, _translate("MainWindow", "45-49"))
        self.comboBoxTrancheAge.setItemText(9, _translate("MainWindow", "50 et plus"))
        self.label_22.setText(_translate("MainWindow", "Préciser la tranche d\'age :"))
        self.groupBoxDepistage.setTitle(_translate("MainWindow", "Information sur le test de dépistage"))
        self.comboBoxConseilDep.setItemText(0, _translate("MainWindow", "Oui"))
        self.comboBoxConseilDep.setItemText(1, _translate("MainWindow", "Non"))
        self.label_24.setText(_translate("MainWindow", "Conseiller pour le test :"))
        self.comboBoxEffectDep.setItemText(0, _translate("MainWindow", "Oui"))
        self.comboBoxEffectDep.setItemText(1, _translate("MainWindow", "Non"))
        self.label_25.setText(_translate("MainWindow", "Effectivement dépisté :"))
        self.comboBoxConseilerAvResult.setItemText(0, _translate("MainWindow", "Oui"))
        self.comboBoxConseilerAvResult.setItemText(1, _translate("MainWindow", "Non"))
        self.label_26.setText(_translate("MainWindow", "Conseiller et dépister ayant reçu son résultat :"))
        self.comboBoxResultat.setItemText(0, _translate("MainWindow", "Négatif"))
        self.comboBoxResultat.setItemText(1, _translate("MainWindow", "Positif"))
        self.comboBoxResultat.setItemText(2, _translate("MainWindow", "Indéterminé"))
        self.comboBoxResultat.setItemText(3, _translate("MainWindow", "Statut connu"))
        self.label_27.setText(_translate("MainWindow", "Résultat du test de dépistage : "))
        self.comboBoxPositifConnaisResultat.setItemText(0, _translate("MainWindow", "Oui"))
        self.comboBoxPositifConnaisResultat.setItemText(1, _translate("MainWindow", "Non"))
        self.label_28.setText(_translate("MainWindow", "Positif ayant reçu son résultat :"))
        self.label_29.setText(_translate("MainWindow", "Positif bénéficiant d\'un CD4 :"))
        self.comboBoxBeneficiantCD4.setItemText(0, _translate("MainWindow", "Oui"))
        self.comboBoxBeneficiantCD4.setItemText(1, _translate("MainWindow", "Non"))
        self.pushButtonAnnuler2.setText(_translate("MainWindow", "Annuler"))
        self.groupBoxFiltre.setTitle(_translate("MainWindow", "Filtre"))
        self.label_6.setText(_translate("MainWindow", "Sexe"))
        self.comboBoxSexe.setItemText(0, _translate("MainWindow", "Tout"))
        self.comboBoxSexe.setItemText(1, _translate("MainWindow", "Masculin"))
        self.comboBoxSexe.setItemText(2, _translate("MainWindow", "Feminin"))
        self.label_3.setText(_translate("MainWindow", "Poste de dépis."))
        self.pushButtonOkFiltre.setText(_translate("MainWindow", "ok"))
        self.radioButtonFiltre.setText(_translate("MainWindow", "Désactiver les filtres"))
        self.groupBoxPeriode.setTitle(_translate("MainWindow", "Période"))
        self.dateEditDebut.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.label_4.setText(_translate("MainWindow", "Debut :"))
        self.label_5.setText(_translate("MainWindow", "Fin :"))
        self.dateEditFin.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.radioButtonAll.setText(_translate("MainWindow", "Tout"))
        self.pushButtonOkPeriode.setText(_translate("MainWindow", "ok"))
        self.labelAppName.setText(_translate("MainWindow", "Outil de Rapportage"))
        self.pushButtonDonnees.setText(_translate("MainWindow", "       Données"))
        self.pushButtonEnregistrement.setText(_translate("MainWindow", "       Enregistrement"))
        self.pushButtonVisualisation.setText(_translate("MainWindow", "       Visualisation"))
        self.pushButtonAccueil.setText(_translate("MainWindow", "       Accueil"))
        self.labelLogo1.setText(_translate("MainWindow", "Repor"))
        self.labelLogo2.setText(_translate("MainWindow", "T"))
        self.labelLogo3.setText(_translate("MainWindow", "ing"))
        self.labelLogo5.setText(_translate("MainWindow", "ool"))
        self.labelAuthor58168122.setText(_translate("MainWindow", "Design by DeepBright"))
        self.pushButtonExporter.setText(_translate("MainWindow", "       Exporter"))
        self.label_32.setText(_translate("MainWindow", "Source"))
        self.comboBoxSource.setItemText(0, _translate("MainWindow", "Excel"))
        self.comboBoxSource.setItemText(1, _translate("MainWindow", "BD"))
        self.labelEnregiestrement.setText(_translate("MainWindow", " Enrégistrement du patient"))
